// Generated by gencpp from file beginner_tutorails/AddTwoInts.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORAILS_MESSAGE_ADDTWOINTS_H
#define BEGINNER_TUTORAILS_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <beginner_tutorails/AddTwoIntsRequest.h>
#include <beginner_tutorails/AddTwoIntsResponse.h>


namespace beginner_tutorails
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace beginner_tutorails


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorails::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::beginner_tutorails::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorails::AddTwoInts > {
  static const char* value()
  {
    return "beginner_tutorails/AddTwoInts";
  }

  static const char* value(const ::beginner_tutorails::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorails::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorails::AddTwoInts > 
template<>
struct MD5Sum< ::beginner_tutorails::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorails::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_tutorails::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorails::AddTwoIntsRequest> should match 
// service_traits::DataType< ::beginner_tutorails::AddTwoInts > 
template<>
struct DataType< ::beginner_tutorails::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorails::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_tutorails::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorails::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorails::AddTwoInts > 
template<>
struct MD5Sum< ::beginner_tutorails::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorails::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_tutorails::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorails::AddTwoIntsResponse> should match 
// service_traits::DataType< ::beginner_tutorails::AddTwoInts > 
template<>
struct DataType< ::beginner_tutorails::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorails::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_tutorails::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORAILS_MESSAGE_ADDTWOINTS_H
